Git-sungtae/Prj_jPanda

jPanda/src/main/resources/mappers/TestMapper.xml
=> mapper 오류 해결

jPanda/src/main/java/com/kakao/jPanda/kts/domain/Member.java, jPanda/src/main/java/com/kakao/jPanda/kts/domain/Partner.java, jPanda/src/main/resources/mappers/kts/chatMapper.xml, jPanda/src/main/resources/templates/kts/chatTestView.html
오류 수정하던 중 GlobalExceptionHandler가 SqlException 메세지를 상세하게 나타내지 않아서 오류 찾기가 쉽지않았어요
=> ERD, Dummy 업데이트 후 Chat 기능 오류 수정

jPanda/src/main/java/com/kakao/jPanda/kyg/controller/ChargeController.java, jPanda/src/main/java/com/kakao/jPanda/kyg/dao/ChargeDao.java, jPanda/src/main/java/com/kakao/jPanda/kyg/dao/ChargeDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/kyg/domain/ChargeDto.java, jPanda/src/main/java/com/kakao/jPanda/kyg/domain/CouponDto.java, jPanda/src/main/java/com/kakao/jPanda/kyg/domain/CouponUseDto.java, jPanda/src/main/java/com/kakao/jPanda/kyg/domain/PaymentDto.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeService.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeServiceImpl.java, jPanda/src/main/resources/configuration.xml, jPanda/src/main/resources/mappers/kyg/ChargeMapper.xml, jPanda/src/main/resources/templates/kyg/chargePage.html
결제방법
금액 입력 후 밤부 계산-> 밤부 입력 후 금액 계산
충전방법 및 보너스율 DTO 생성
결제내역 DTO 생성
configuration 생성
최신 dev Merge
=> 밤부결제방법 변경, 충전방법출력 변경, DTO 생성

jPanda/src/main/java/com/kakao/jPanda/kyg/controller/ChargeController.java, jPanda/src/main/java/com/kakao/jPanda/kyg/dao/ChargeDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeServiceImpl.java, jPanda/src/main/resources/mappers/kyg/ChargeMapper.xml, jPanda/src/main/resources/templates/kyg/chargePage.html
기존 : 임의의 ID를 만들어 사용
수정 : login된 session의 정보를 charge관련 DTO에 전달
=> ID Validation 방식 변경

jPanda/src/main/java/com/kakao/jPanda/kyg/controller/ChargeController.java, jPanda/src/main/java/com/kakao/jPanda/kyg/dao/ChargeDao.java, jPanda/src/main/java/com/kakao/jPanda/kyg/dao/ChargeDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/kyg/domain/ChargeHistoryDto.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeService.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeServiceImpl.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/Paging.java, jPanda/src/main/resources/mappers/kyg/ChargeMapper.xml, jPanda/src/main/resources/templates/kyg/chargePage.html
loginId -> memberId 변경
충전내역 구현
불필요한 코드 제거
=> login 수정, 충전내역 구현

jPanda/src/main/java/com/kakao/jPanda/kyg/controller/ChargeController.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeServiceImpl.java, jPanda/src/main/resources/mappers/kyg/ChargeMapper.xml, jPanda/src/main/resources/templates/kyg/chargePage.html
Timestamp 날짜표시 밀리초 제거
충전방법 충전금액 위치 변경
충전페이지 /제거
불필요한 코드 및 주석 제거
=> 결제내역 날짜표시범위 변경

jPanda/src/main/java/com/kakao/jPanda/njb/controller/MemberController.java, jPanda/src/main/java/com/kakao/jPanda/njb/dao/MemberDao.java, jPanda/src/main/java/com/kakao/jPanda/njb/dao/MemberDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/njb/service/MemberService.java, jPanda/src/main/java/com/kakao/jPanda/njb/service/MemberServiceImpl.java, jPanda/src/main/resources/mappers/njb/MemberMapper.xml, jPanda/src/main/resources/templates/njb/mypage.html
=> 회원가입시 자동 normal_role, 회원탈퇴기능,로그인시 normal_role

jPanda/src/main/java/com/kakao/jPanda/kyg/controller/ChargeController.java, jPanda/src/main/java/com/kakao/jPanda/kyg/dao/ChargeDao.java, jPanda/src/main/java/com/kakao/jPanda/kyg/dao/ChargeDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/kyg/domain/ChargeHistoryDto.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeService.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeServiceImpl.java, jPanda/src/main/resources/mappers/kyg/ChargeMapper.xml, jPanda/src/main/resources/templates/kyg/chargePage.html
충전로직 기존 : 쿠폰사용가능시 충전밤부, 충전방법 변경 불가
충전로직 수정 : 쿠폰적용시 충전밤부, 충전방법 변경 가능 및 계산오류 수정
충전내역 밤부 추가
공통레이아웃 적용
충전내역 충전방법 네이밍 변경
=> 충전로직 변경, 충전내역 밤부 추가

jPanda/src/main/java/com/kakao/jPanda/kts/controller/ChatController.java, jPanda/src/main/resources/templates/common/default.html, jPanda/src/main/resources/templates/common/script/chat-js.html, jPanda/src/main/resources/templates/common/script/header-js.html
sessionStorage.key()로 가져오면 해결됨
memberId가 guest인 경우도 chat기능에서 로그인 한걸로 인식하므로 memberId에 'guest'값 할당하는 로직
지워야함
=> Layout Session Error 해결 및 일부 수정

jPanda/src/main/resources/templates/bsm/talentUpdateForm.html, jPanda/src/main/resources/templates/bsm/talentWriteForm.html
재능 등록 - 카테고리가 나오지 않는 오류 수정
재능 등록,수정 - 가격 입력란 숫자, backspace외 입력 불가 처리 완료
그리고 sessionStorage.key('memberId') 이거 써봤는데 null값만 나와여
=> 재능 등록,수정 페이지 오류 수정

jPanda/src/main/java/com/kakao/jPanda/jst/dao/TradeDao.java, jPanda/src/main/java/com/kakao/jPanda/jst/dao/TradeDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/jst/handler/TradeWebSocketHandler.java, jPanda/src/main/java/com/kakao/jPanda/jst/service/TradeServiceImpl.java, jPanda/src/main/resources/templates/common/fragment/chat.html, jPanda/src/main/resources/templates/common/script/chat-js.html, jPanda/src/main/resources/templates/common/style/chat-css.html
채팅 날짜 및 시간 표시
콘솔창 닫힌 상태에서 메세지 수신시 메세지 버튼 애니메이션 추가
읽지 않은 메세지 갯수 표시예정
=> Chat 일부 기능

jPanda/src/main/java/com/kakao/jPanda/kyg/controller/ChargeController.java, jPanda/src/main/java/com/kakao/jPanda/kyg/dao/ChargeDao.java, jPanda/src/main/java/com/kakao/jPanda/kyg/dao/ChargeDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/kyg/domain/ChargeDto.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeService.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeServiceImpl.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/Paging.java, jPanda/src/main/resources/mappers/kyg/ChargeMapper.xml, jPanda/src/main/resources/templates/kyg/chargeHistoryPage.html, jPanda/src/main/resources/templates/kyg/chargePage.html
페이징 - 충전내역에 따른 결제정보 확인가능
페이지 버튼클릭시 오작동 - show/hide로 인한 display 오류
chargeHistoryPage 작성 후 href
client 충전정보 가독성 향상작업
=> 충전/내역 페이징작업 완료, 페이지 버튼클릭시 오작동 수정

jPanda/src/main/java/com/kakao/jPanda/kyg/controller/ChargeController.java, jPanda/src/main/java/com/kakao/jPanda/kyg/dao/ChargeDao.java, jPanda/src/main/java/com/kakao/jPanda/kyg/dao/ChargeDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/kyg/domain/ChargeDto.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeService.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeServiceImpl.java, jPanda/src/main/resources/mappers/kyg/ChargeMapper.xml, jPanda/src/main/resources/templates/kyg/chargeHistoryPage.html, jPanda/src/main/resources/templates/kyg/chargePage.html
기존의 mapper and연산자 -> BETWEEN
naming parameter가 변경됨에 따라 naming 수정
chargeInsert의 명확한 의미전달을 위해 paymentAmount -> chargeMoney로 수정
paging 10페이지 이후의 next로 넘어갈 시 오류 수정
table의 우측에 페이징출력 수정 및 부트스트랩 사용 가독성 향상
=> 충전/내역 mapper수정, naming수정, 페이징수정

jPanda/src/main/java/com/kakao/jPanda/kyg/controller/ChargeController.java, jPanda/src/main/java/com/kakao/jPanda/kyg/domain/ChargeDto.java, jPanda/src/main/resources/mappers/kyg/ChargeMapper.xml, jPanda/src/main/resources/templates/kyg/chargeHistoryPage.html, jPanda/src/main/resources/templates/kyg/chargePage.html
naming erd column에 맞게 수정 및 자연스러운 naming 변경
table 결제출력번호 삭제 및 총 충전내역 출력
잘못된 log출력 변경
작동테스트 완료
=> 충전/내역 naming 정정 및 충전내역 변경

jPanda/src/main/java/com/kakao/jPanda/kts/config/WebSocketStompConfig.java, jPanda/src/main/java/com/kakao/jPanda/kts/controller/ChatController.java, jPanda/src/main/java/com/kakao/jPanda/kts/dao/ChatDao.java, jPanda/src/main/java/com/kakao/jPanda/kts/dao/impl/ChatDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/kts/domain/Chat.java, jPanda/src/main/java/com/kakao/jPanda/kts/domain/Partner.java, jPanda/src/main/java/com/kakao/jPanda/kts/service/ChatService.java, jPanda/src/main/java/com/kakao/jPanda/kts/service/impl/ChatServiceImpl.java, jPanda/src/main/resources/mappers/kts/chatMapper.xml, jPanda/src/main/resources/templates/common/fragment/chat.html, jPanda/src/main/resources/templates/common/script/chat-js.html, jPanda/src/main/resources/templates/common/style/chat-css.html
1.메세지 전송 방식 변경(SimpMessagingTemplate) 사용
2.채팅 상대 목록에 안읽은 메세지 수 표기
3.실시간 읽음 여부 확인 기능 추가
4.채팅창 float -> grid 변경
5.일부 log 수정
=> Chat 기능 추가

jPanda/src/main/resources/templates/bsm/notice.html
공시사항 검색기능 상단 검색 메뉴와 id중복으로 id변경으로 값을 가져오지 못한 오류 수정
hash사용으로 현재페이지에서 공지사항 상세를 누르고 뒤로가기,목록 클릭 시 1페이지가 아닌 기존 페이지로 가도록 기능 추가
=> 공지사항 페이지 기능 추가 및 변경

jPanda/src/main/resources/templates/kyg/chargeHistoryPage.html
충전번호 1~10 반복되어 출력되는 문제 해결 후 추가
=> 충전/내역 충전내역 번호 출력 수정

jPanda/src/main/java/com/kakao/jPanda/kyg/controller/ChargeController.java, jPanda/src/main/resources/templates/common/fragment/header.html, jPanda/src/main/resources/templates/common/script/header-js.html, jPanda/src/main/resources/templates/common/style/header-css.html
header에 출력되는 총 보유 밤부의 로그인 여부에 따른 출력여부 수정
memberId를 controller에서 비교하는것이 아닌 client에서 비교
=> 충전/내역 로그인/비로그인에 따른 총밤부출력 여부 수정

jPanda/src/main/java/com/kakao/jPanda/jst/controller/TradeController.java, jPanda/src/main/java/com/kakao/jPanda/jst/dao/TradeDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/jst/handler/TradeWebSocketHandler.java, jPanda/src/main/java/com/kakao/jPanda/jst/service/TradeService.java, jPanda/src/main/java/com/kakao/jPanda/jst/service/TradeServiceImpl.java, jPanda/src/main/resources/mappers/jst/TradeMapper.xml, jPanda/src/main/resources/templates/jst/trade.html
1) ResponseEntity로 Http Status 리턴하는 방식으로 변경
2) Handler 메서드에 Null처리
3) 구매수가 0인경우 환전신청 못하도록 변경
=> 거래관리 Response방식 변경, null처리, 데이터 validation

jPanda/src/main/java/com/kakao/jPanda/yjh/controller/AdminController.java, jPanda/src/main/java/com/kakao/jPanda/yjh/dao/AdminDao.java, jPanda/src/main/java/com/kakao/jPanda/yjh/dao/AdminDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/yjh/domain/Pagination.java, jPanda/src/main/java/com/kakao/jPanda/yjh/domain/ReportDto.java, jPanda/src/main/java/com/kakao/jPanda/yjh/service/AdminService.java, jPanda/src/main/java/com/kakao/jPanda/yjh/service/AdminServiceImpl.java, jPanda/src/main/resources/configuration.xml, jPanda/src/main/resources/mappers/yjh/CouponMapper.xml, jPanda/src/main/resources/mappers/yjh/ExchangeMapper.xml, jPanda/src/main/resources/mappers/yjh/NoticeMapper.xml, jPanda/src/main/resources/mappers/yjh/TalentMapper.xml, jPanda/src/main/resources/mappers/yjh/TalentRefundMapper.xml, jPanda/src/main/resources/templates/common/fragment/admin-nav.html, jPanda/src/main/resources/templates/yjh/company-sales.html, jPanda/src/main/resources/templates/yjh/createCoupon.html, jPanda/src/main/resources/templates/yjh/exchange.html, jPanda/src/main/resources/templates/yjh/home.html, jPanda/src/main/resources/templates/yjh/notice-content.html, jPanda/src/main/resources/templates/yjh/notice-form.html, jPanda/src/main/resources/templates/yjh/notice-modifyFrom.html, jPanda/src/main/resources/templates/yjh/notice.html, jPanda/src/main/resources/templates/yjh/report.html, jPanda/src/main/resources/templates/yjh/talent-detail.html, jPanda/src/main/resources/templates/yjh/talent-refund.html, jPanda/src/main/resources/templates/yjh/talent.html
=> 관리자 페이지 게시판형 페이지 페이징 작업

jPanda/src/main/resources/templates/common/fragment/chat.html, jPanda/src/main/resources/templates/common/script/chat-js.html, jPanda/src/main/resources/templates/common/script/common-js.html
1.신규 메세지 신고 모달창 에러 해결
2.모든 페이지에서 session의 memberId 사용가능하도록 common-js로 옮김 
3.chat-js 리팩토링
=> Chat 오류 수정, memberId 공용처리

jPanda/src/main/resources/templates/common/script/header-js.html
통합검색란 입력후 엔터시 현재페이지가 새로고침이 되는 오류 수정
=> 헤더 스크립트 수정

jPanda/src/main/java/com/kakao/jPanda/kyg/controller/ChargeController.java, jPanda/src/main/java/com/kakao/jPanda/kyg/dao/ChargeDao.java, jPanda/src/main/java/com/kakao/jPanda/kyg/dao/ChargeDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/kyg/domain/Pagination.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeService.java, jPanda/src/main/java/com/kakao/jPanda/kyg/service/ChargeServiceImpl.java, jPanda/src/main/resources/templates/common/fragment/header.html, jPanda/src/main/resources/templates/kyg/chargeHistoryPage.html
기존 - controller를 통해 page를 이동할때마다 값을 전달
수정 - ajax를 이용, page이동할때마다 값을 일일이 불러오지 않음
=> 충전/내역 충전내역 출력방법 변경

jPanda/src/main/resources/mappers/kts/chatMapper.xml, jPanda/src/main/resources/templates/common/script/chat-js.html
=> Chat seq 오류 수정

jPanda/src/main/resources/templates/common/script/chat-js.html, jPanda/src/main/resources/templates/common/style/chat-css.html
=> Chat 신고 기능을 위한 Tooltip 추가

jPanda/src/main/resources/mappers/yjh/TalentRefundMapper.xml, jPanda/src/main/resources/templates/yjh/company-sales.html, jPanda/src/main/resources/templates/yjh/createCoupon.html, jPanda/src/main/resources/templates/yjh/exchange.html, jPanda/src/main/resources/templates/yjh/home.html, jPanda/src/main/resources/templates/yjh/notice-content.html, jPanda/src/main/resources/templates/yjh/notice-form.html, jPanda/src/main/resources/templates/yjh/notice-modifyFrom.html, jPanda/src/main/resources/templates/yjh/notice.html, jPanda/src/main/resources/templates/yjh/report.html, jPanda/src/main/resources/templates/yjh/talent-detail.html, jPanda/src/main/resources/templates/yjh/talent-refund.html, jPanda/src/main/resources/templates/yjh/talent.html
관리자 페이지 refund mapper 수정, css 작업중
=> 관리자 페이지 refund mapper 수정, css 작업중

jPanda/src/main/resources/templates/common/fragment/chat.html, jPanda/src/main/resources/templates/common/script/chat-js.html, jPanda/src/main/resources/templates/common/style/chat-css.html
=> Chat 스타일 변경

jPanda/src/main/resources/templates/jst/trade.html
=> 거래관리 환불 반려 후처리 로직 추가

jPanda/src/main/resources/templates/common/fragment/footer.html
=> layout footer 변경

jPanda/src/main/java/com/kakao/jPanda/common/annotation/NoLoginCheck.java, jPanda/src/main/java/com/kakao/jPanda/common/config/WebMvcConfig.java, jPanda/src/main/java/com/kakao/jPanda/common/interceptor/CommonInterceptor.java, jPanda/src/main/java/com/kakao/jPanda/jst/controller/TradeController.java
1) Annotation을 통해 핸들러 포함/비포함 Path 구분
2) @NoLoginCheck를 붙인 url은 로그인체크 제거
=> 공통 로그인체크 Interceptor 구현

jPanda/src/main/java/com/kakao/jPanda/common/config/WebMvcConfig.java, jPanda/src/main/java/com/kakao/jPanda/common/interceptor/CommonInterceptor.java, jPanda/src/main/resources/templates/jst/trade.html
1) 인터셉터 비동기처리 미작동 문제 수정
2) 인터셉터 비동기 xhr.responseText의 redirectionUrl로 replace하도록 ajax 콜백함수 수정
=> 공통 인터셉터 수정, 거래관리 ajax 에러처리

jPanda/src/main/resources/templates/common/script/chat-js.html, jPanda/src/main/resources/templates/common/script/footer-js.html
1.chat-js 재능 상담 버튼 눌렀을때 채팅창 열리자 마자 닫히는 현상 방지 코드 추가
2.footer-js 관리자 상담 버튼 눌렀을때 로그인 안했으면 로그인 하라고 알림
=> Chat 재능 상담 채팅기능 추가에 맞춰 수정

jPanda/src/main/java/com/kakao/jPanda/bsm/controller/PageController.java, jPanda/src/main/java/com/kakao/jPanda/bsm/service/RegistTalentServiceImpl.java, jPanda/src/main/resources/templates/bsm/main.html
이미지 저장 경로 수정
정상적인 접근이어도 비정상적인 접근으로 잡던 오류 확인 및 변경
=> 재능등록,수정 페이지 수정

jPanda/src/main/java/com/kakao/jPanda/common/config/WebMvcConfig.java, jPanda/src/main/java/com/kakao/jPanda/common/exception/ControllerExceptionHandler.java, jPanda/src/main/java/com/kakao/jPanda/common/exception/CustomException.java, jPanda/src/main/java/com/kakao/jPanda/common/exception/ErrorCode.java, jPanda/src/main/java/com/kakao/jPanda/common/exception/ErrorResponseEntity.java, jPanda/src/main/java/com/kakao/jPanda/common/interceptor/CommonInterceptor.java, jPanda/src/main/java/com/kakao/jPanda/jst/controller/TradeController.java, jPanda/src/main/resources/templates/common/script/common-js.html, jPanda/src/main/resources/templates/jst/trade.html
1) custom exception, runtime exception 분리해서 처리
2) 에러처리 로직 모듈화
3) 공통 JS에 handleError() 추가
=> 공통 Exception Handling 공통화 

jPanda/src/main/java/com/kakao/jPanda/bsm/service/RegistTalentServiceImpl.java, jPanda/src/main/resources/templates/bsm/notice.html, jPanda/src/main/resources/templates/bsm/talentWriteForm.html
=> 공지사항, 재능등록,수정 페이지 수정

jPanda/src/main/resources/templates/common/script/header-js.html
1) 공통 로그아웃시 이동 url 변경
2) 로그인 logout기능 validation 제외
=> 공통 로그아웃 기능 변경

jPanda/src/main/java/com/kakao/jPanda/bsm/dao/RegistTalentDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/bsm/service/RegistTalentServiceImpl.java
=> 재능 수정 페이지 수정

jPanda/src/main/java/com/kakao/jPanda/lhw/dao/TalentDao.java, jPanda/src/main/java/com/kakao/jPanda/lhw/dao/TalentDaoImpl.java, jPanda/src/main/java/com/kakao/jPanda/lhw/service/TalentServiceImpl.java, jPanda/src/main/resources/mappers/lhw/TalentMapper.xml, jPanda/src/main/resources/templates/lhw/board.html, jPanda/src/main/resources/templates/lhw/talent.html
=> 판매 게시판 기능 최종본 중복 리뷰 인서트 추가

jPanda/src/main/resources/templates/talent/register/talent-update-form.html
재능 수정 시 입력하지 않거나 조건을 만족하지 않아도 사이드바에 체크표시가 되는 오류 수정
=> 재능 수정 페이지 오류 수정

jPanda/src/main/resources/templates/charge/charge-history.html, jPanda/src/main/resources/templates/charge/charge.html
JS console 삭제
client 이해 향상을 위해 할인율 % 추가 및 밤부 충전 비율 추가
title 충전 / 결제내역 분리
=> 충전/내역 console 삭제, client 내용 추가, title 변경

jPanda/src/main/resources/templates/admin/create-coupon.html, jPanda/src/main/resources/templates/admin/exchange.html, jPanda/src/main/resources/templates/admin/notice-content.html, jPanda/src/main/resources/templates/admin/notice-form.html, jPanda/src/main/resources/templates/admin/notice-modify-form.html, jPanda/src/main/resources/templates/admin/notice.html, jPanda/src/main/resources/templates/admin/report.html, jPanda/src/main/resources/templates/admin/talent-refund.html, jPanda/src/main/resources/templates/admin/talent.html
=> admin pagination수정, css 작업 중

jPanda/src/main/resources/templates/board/board.html, jPanda/src/main/resources/templates/talent/detail/talent.html
=> 판매 게시판 CSS 최종 수정

jPanda/src/main/resources/templates/trade/trade.html
=> 거래관리 layout Collapse 수정

jPanda/src/main/resources/templates/admin/company-sales.html, jPanda/src/main/resources/templates/admin/create-coupon.html, jPanda/src/main/resources/templates/admin/exchange.html, jPanda/src/main/resources/templates/admin/notice.html, jPanda/src/main/resources/templates/admin/report.html, jPanda/src/main/resources/templates/admin/talent-detail.html, jPanda/src/main/resources/templates/admin/talent-refund.html, jPanda/src/main/resources/templates/admin/talent.html
=> admin css 작업 완료

jPanda/src/main/java/com/kakao/jPanda/common/exception/ControllerExceptionHandler.java, jPanda/src/main/java/com/kakao/jPanda/common/interceptor/CommonInterceptor.java, jPanda/src/main/resources/static/css/board.css, jPanda/src/main/resources/templates/trade/trade.html
1) Exception Handler 모든 ajax요청을 catch 하지못하는 부분 수정
2) 거래관리 bs 카드 css 수정
=> 공통 Exception Handler 수정, 거래관리 css 수정
